package com.java.db.mybatis.xml.entity;

import java.io.Serializable;
import java.util.Date;

public class City implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CITYCODE
     *
     * @mbg.generated
     */
    private String citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CITYNAME
     *
     * @mbg.generated
     */
    private String cityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.STARTTIME
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.ENDTIME
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.PERCENT
     *
     * @mbg.generated
     */
    private Long percent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.QUERYTIME
     *
     * @mbg.generated
     */
    private Date querytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CONFIRMTIME
     *
     * @mbg.generated
     */
    private Date confirmtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CITYCODE
     *
     * @return the value of city.CITYCODE
     *
     * @mbg.generated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CITYCODE
     *
     * @param citycode the value for city.CITYCODE
     *
     * @mbg.generated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CITYNAME
     *
     * @return the value of city.CITYNAME
     *
     * @mbg.generated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CITYNAME
     *
     * @param cityname the value for city.CITYNAME
     *
     * @mbg.generated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.STARTTIME
     *
     * @return the value of city.STARTTIME
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.STARTTIME
     *
     * @param starttime the value for city.STARTTIME
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.ENDTIME
     *
     * @return the value of city.ENDTIME
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.ENDTIME
     *
     * @param endtime the value for city.ENDTIME
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.PERCENT
     *
     * @return the value of city.PERCENT
     *
     * @mbg.generated
     */
    public Long getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.PERCENT
     *
     * @param percent the value for city.PERCENT
     *
     * @mbg.generated
     */
    public void setPercent(Long percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.QUERYTIME
     *
     * @return the value of city.QUERYTIME
     *
     * @mbg.generated
     */
    public Date getQuerytime() {
        return querytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.QUERYTIME
     *
     * @param querytime the value for city.QUERYTIME
     *
     * @mbg.generated
     */
    public void setQuerytime(Date querytime) {
        this.querytime = querytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CONFIRMTIME
     *
     * @return the value of city.CONFIRMTIME
     *
     * @mbg.generated
     */
    public Date getConfirmtime() {
        return confirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CONFIRMTIME
     *
     * @param confirmtime the value for city.CONFIRMTIME
     *
     * @mbg.generated
     */
    public void setConfirmtime(Date confirmtime) {
        this.confirmtime = confirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", citycode=").append(citycode);
        sb.append(", cityname=").append(cityname);
        sb.append(", starttime=").append(starttime);
        sb.append(", endtime=").append(endtime);
        sb.append(", percent=").append(percent);
        sb.append(", querytime=").append(querytime);
        sb.append(", confirmtime=").append(confirmtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}