package com.java.db.mybatis.xml.dao;

import com.java.db.mybatis.xml.entity.Provincial;
import java.util.List;

public interface ProvincialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer provincialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbg.generated
     */
    int insert(Provincial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbg.generated
     */
    Provincial selectByPrimaryKey(Integer provincialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbg.generated
     */
    List<Provincial> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provincial
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Provincial record);
}